package repository

import comicModel "github.com/brayanlopez8/GolangComicsStore/internal/model"

//ComicRepositoryInterface ....
type ComicRepositoryInterface interface {

	// Find retrieves a user from database based on a comic's id
	Find(id int) (*comicModel.Comic, error)

	// FindByName retrieves a user from database by User.Name
	// FindByName(name string) (user *model.Comic, err error)

	// FindAll retrieves all Comic from database as an array of user
	FindAll() ([]comicModel.Comic, error)

	// Update changes user information on the User.Id passed in.
	Update(user *comicModel.Comic) (rowsAffected int64, err error)

	// Insert adds a Comic to a database. The returned resultComic has a Id, which is auto generated by database
	Insert(user *comicModel.Comic) (resultComic *comicModel.Comic, err error)
}
